version: "3.9"

services:
  spotify-playlist-app:
    build: .
    container_name: spotify_playlist_app
    environment:
      - CLIENT_ID=${CLIENT_ID}
      - CLIENT_SECRET=${CLIENT_SECRET}
      - REDIRECT_URI=http://127.0.0.1:8888/callback
    ports:
      - "8888:8888"
    volumes:
      - .:/app
